extends Node

var items = {
	"wieldhand":{
		"type":"item",
		"max_count":1,
		"inv_image":"res://res/textures/wieldhand.png",
		"punch_interval":1,
		"damage":1,
		"speed":0.5,
		"tool_ability":{
			"crumbly":1,
			"choppy":1,
			"snappy":1,
			"loose":100,
		},
	},
	"dev_pick":{
		"max_count":1,
		"type":"item",
		"inv_image":"res://res/textures/pick_stone.png",
		"punch_interval":1,
		"speed":15,
		"damage":1,
		"tool_ability":{
			"cracky":1000,
			"crumbly":1000,
			"choppy":1000,
			"snappy":1000,
		},
		"color_overlay":Color(1,0,1),
	},
	"stone_pick":{
		"max_count":1,
		"type":"item",
		"inv_image":"res://res/textures/pick_stone.png",
		"punch_interval":1,
		"damage":1,
		"durability":100,
		"tool_ability":{
			"cracky":1,
		},
		"craft":{
			"recipe":[
				"group:stone","group:stone","group:stone",
				"","group:stick","",
				"","group:stick","",]
		}
	},
	"stone_hoe":{
		"max_count":1,
		"type":"item",
		"inv_image":"res://res/textures/hoe_stone.png",
		"punch_interval":1,
		"damage":1,
		"durability":100,
		"tool_ability":{
			"crumbly":1,
		},
		"craft":{
			"recipe":[
				"group:stone","group:stone","",
				"","group:stick","",
				"","group:stick","",]
		}	
	},
	"stone_shovel":{
		"max_count":1,
		"type":"item",
		"inv_image":"res://res/textures/shovel_stone.png",
		"punch_interval":1,
		"damage":1,
		"durability":100,
		"tool_ability":{
			"crumbly":2,
		},
		"craft":{
			"recipe":[
				"","group:stone","",
				"","group:stick","",
				"","group:stick","",]
		}
	},
	"axe_stone":{
		"max_count":1,
		"type":"item",
		"inv_image":"res://res/textures/axe_stone.png",
		"punch_interval":1,
		"damage":1,
		"durability":100,
		"tool_ability":{
			"choppy":1,
		},
		"craft":{
			"recipe":[
				"group:stone","group:stone","",
				"group:stone","group:stick","",
				"","group:stick","",]
		}
	},
	"stick":{
		"max_count":100,
		"type":"item",
		"inv_image":"res://res/textures/stick.png",
		"groups":{"stick":1},
		"craft":{
			"count":4,
			"recipe":["group:wood"],
		}
	},
#nodes ==============
	"air":{
		"type":"node",
		"pointable":false,
		"replaceable":true,
		"transparency":"alpha",
		"solid":false,
		"sounds":{"step":"","dig":"","dug":"","place":""},
	},
	"stone":{
		"type":"node",
		"tiles":["res://res/textures/stone.png"],
		"groups":{"cracky":1,"stone":1},
		"sounds":{"step":"res://res/sounds/step/stone.ogg","dig":"res://res/sounds/place_dig/stone_dig.ogg","dug":"res://res/sounds/place_dig/stone_dug.ogg","place":"res://res/sounds/place_dig/place_hard.ogg"},
	},
	"grassy":{
		"type":"node",
		"drop":{"item":"dirt","count":1},
		"inv_image":"res://res/textures/grass_dirt.png",
		"tiles":[
			"res://res/textures/grass.png",
			"res://res/textures/dirt.png",
			"res://res/textures/grass_dirt.png"],
		"groups":{"crumbly":1},
		"craft":{
			"count":1,
			"recipe":["dirt"],
		},
		"sounds":{"step":"res://res/sounds/step/grass.ogg","dig":"res://res/sounds/step/leaves.ogg","dug":"res://res/sounds/step/leaves.ogg","place":"res://res/sounds/place_dig/place.ogg"},
	},
	"dirt":{
		"type":"node",
		"speed":2,
		"inv_image":"res://res/textures/dirt.png",
		"tiles":["res://res/textures/dirt.png"],
		"groups":{"crumbly":1},
		"sounds":{"step":"res://res/sounds/step/grass.ogg","dig":"res://res/sounds/step/leaves.ogg","dug":"res://res/sounds/step/leaves.ogg","place":"res://res/sounds/place_dig/place.ogg"},
	},
	"wood":{
		"type":"node",
		"tiles":["res://res/textures/wood.png"],
		"groups":{"wood":1,"choppy":1},
		"craft":{
			"count":1,
			"recipe":[
				"group:tree","group:stick","",
				"group:stick","group:stick",
			],
		},
		"sounds":{"step":"res://res/sounds/step/wood.ogg","dig":"res://res/sounds/place_dig/wood_dig.ogg","dug":"res://res/sounds/place_dig/wood_dug.ogg","place":"res://res/sounds/place_dig/place_hard.ogg"},
	},
	"water":{"type":"node",
		"node_type":"liquid",
		"pointable":false,
		"solid":false,
		"replaceable":true,
		"viscosity":0.25,
		"gravity":0.1,
		"fluid":true,
		"transparency":"alpha",
		"tiles":["res://res/textures/water.png"],
		"sounds":{"step":"res://res/sounds/water/water_swim.ogg","dig":"res://res/sounds/water/water_swim.ogg","dug":"res://res/sounds/water/water_swim.ogg","place":"res://res/sounds/water/water_pour.ogg"},
	},
	"grass1":{"type":"node",
		"drawtype":"simple_cross",
		"solid":false,
		"replaceable":true,
		"transparency":"scissor",
		"groups":{"loose":100},
		"tiles":["res://res/textures/plants/grass5.png"],
		"sounds":{"dig":"res://res/sounds/step/leaves.ogg","dug":"res://res/sounds/step/leaves.ogg","place":"res://res/sounds/place_dig/place.ogg"},
	},
	"fire":{"type":"node",
		"node_type":"fire",
		"drawtype":"boxed_cross",
		"solid":false,
		"replaceable":true,
		"transparency":"scissor",
		"uv_scale":Vector2(1,8),
		"shading":false,
		"light_color":Color(1,0.5,0),
		"light_energy":8,
		"groups":{"loose":100},
		"animation":{"speed":10,"frames":Vector2(0,8),"tile":0},
		"tiles":["res://res/textures/misc/fire_animated.png"],
		"inv_image":"res://res/textures/misc/fire.png",
		"sounds":{"place":"res://res/sounds/place_dig/place.ogg"},
	},
	"chest":{
		"type":"node",
		"dynamic":true,
		"inv_image":"res://res/textures/chest_front.png",
		"tiles":[
			"res://res/textures/chest_top.png",
			"res://res/textures/chest_top.png",
			"res://res/textures/chest_side.png",
			"res://res/textures/chest_side.png",
			"res://res/textures/chest_front.png",
			"res://res/textures/chest_side.png",
			
		],
		"groups":{"choppy":1},
		"craft":{
			"count":1,
			"recipe":[
				"group:wood","group:wood","group:wood",
				"group:wood","","group:wood","group:wood",
				"group:wood","group:wood","group:wood"
			],
		},
		"sounds":{"step":"res://res/sounds/step/wood.ogg","dig":"res://res/sounds/place_dig/wood_dig.ogg","dug":"res://res/sounds/place_dig/wood_dug.ogg","place":"res://res/sounds/place_dig/place_hard.ogg"},
		"on_activate":func(_pos,player_id):
			gui.show_gui(player_id,{
			"background":{"size":Vector2(8,8.5)},
			"inv":[
				{"name":"main","ref":"current_node","pos":Vector2(0,0),"size":Vector2(8,4)},
				{"name":"main","ref":player_id,"pos":Vector2(0,4.5),"size":Vector2(8,4)},
				]}
			)
			return false
			,
		"on_construct":func(pos):
			core.world.set_node_meta(pos,{"main":stuff.new_inventory()})
			,
		"can_break":func(pos,_id):
			for item in stuff.get_inventory(pos,"main"):
				if item != null:
					return false
			return true
			,
		"on_place":func(pos,id):
			core.getnode(pos).meshinstance.rotation.y = core.from_object_facedir(id)
			,
	},
	"apple":{
		"name":"apple",
		"type":"node",
		"groups":{"loose":100},
		"tiles":["res://res/textures/plants/apple.png"],
		"drawtype":"simple_cross",
		"transparency":"scissor",
		"speed":10,
		"scale":0.5,
		"pointable":true,
		"solid":false,
		"sounds":{"dig":"res://res/sounds/step/leaves.ogg","dug":"res://res/sounds/step/leaves.ogg","place":"res://res/sounds/place_dig/place.ogg"},
	},
	"apple_tree":{
		"type":"node",
		"groups":{"choppy":1,"burnable":5},
		"tiles":[
			"res://res/textures/plants/apple_tree_top.png",
			"res://res/textures/plants/apple_tree_top.png",
			"res://res/textures/plants/apple_tree.png"
		],
		"sounds":{"step":"res://res/sounds/step/wood.ogg","dig":"res://res/sounds/place_dig/wood_dig.ogg","dug":"res://res/sounds/place_dig/wood_dug.ogg","place":"res://res/sounds/place_dig/place_hard.ogg"},
	},
	"apple_tree_leaves":{
		"type":"node",
		"transparency":"scissor",
		"groups":{"snappy":1,"burnable":1},
		"tiles":["res://res/textures/plants/apple_leaves.png"],
		"sounds":{"step":"res://res/sounds/step/leaves.ogg","dig":"res://res/sounds/step/leaves.ogg","dug":"res://res/sounds/step/leaves.ogg","place":"res://res/sounds/place_dig/place.ogg"
		}
	},
}

var mapgen_scatter = {

}
